name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: ./latest
          file: ./latest/Dockerfile
          push: true
          tags: stephenc01/n8n_custom:latest
      -
        name: Build and push next
        uses: docker/build-push-action@v5
        with:
          context: ./next
          file: ./next/Dockerfile
          push: true
          tags: stephenc01/n8n_custom:next

